package entity;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class NodeAttributesTest {
	@Test
	public void testSomeLibraryMethod() {
		NodeAttributes classUnderTest = new NodeAttributes();
		assertEquals(NodeAttributes.ANONYMOUS, classUnderTest.getName());
	}
}
